Repository studygolang/GCTT, pull requests merged in 2019-11, with the labels that each got.

#1461 【翻译完成】 20190715-Passing-callbacks-and-pointers-to-Cgo
  translated/tech/20190715-Passing-callbacks-and-pointers-to-Cgo.md
Labels: request changes, 校对完成

#1417 【翻译完成】20190829-Module-Mirror-and-Checksum-Database-Launched
  translated/tech/20190829-Module-Mirror-and-Checksum-Database-Launched.md
Labels: 校对完成

#1434 【翻译完成】20190807-overview-of-compiler
  translated/tech/20171117-Golang-tutorial-series/20190807-overview-of-compiler.md
Labels: 校对完成

#1406 Translate Garbage Collection In Go : Part III - GC Pacing
  translated/tech/20190718-Garbage-Collection-In-Go-Part-III-GC-Pacing.md
Labels: request changes, 校对完成

#1477 翻译完成 modules-part-01-why-and-what
  translated/tech/20191010-modules-01-why-and-what.md
Labels: request changes, 校对完成

#1369 【翻译完成】20170912 Go Project Layout
  translated/tech/20170912 Go Project Layout.md
Labels: request changes, 校对完成

#1444 【翻译完成】20190905-Logging-HTTP-requests-in-Go.md
  translated/tech/20190905-Logging-HTTP-requests-in-Go.md
Labels: 校对中

#1457 【翻译完成】 20190907-Go—build-a-minimal-docker-image-in-just-three-steps
  translated/tech/20190907-Go-build-a-minimal-docker-image-in-just-three-steps.md
Labels: 校对完成

#1459 【翻译完成】 20190920-Rate Limiting HTTP Requests in Go based on IP address
  translated/tech/20190920-Rate Limiting HTTP Requests in Go based on IP address.md
Labels: 校对完成

#1327 【完成翻译】20190703 Add new statement for go part1
  translated/tech/20190703-Go-compiler-internals-adding-a-new-statement-to-Go-Part-1.md
Labels: 校对完成

#1474 翻译完成 20190521-Go-Is-the-encoding-json-Package-Really-Slow
  translated/tech/20190521-Go-Is-the-encoding-json-Package-Really-Slow.md
Labels: 校对完成

#1490 翻译完成 20190805-Inclusion-No-Go-Files-in-a-Go-Program
  translated/tech/20190805-Inclusion-No-Go-Files-in-a-Go-Program.md
Labels: 校对完成

#1484 翻译完成 20191030 Graceful Restart in Golang
  translated/tech/20191030-Graceful-Restart-in-Golang.md
Labels: 校对完成

#1486 翻译完成 Publishing Go Modules
  translated/tech/20190926-publishing-go-modules.md
Labels: 校对完成
