Repository studygolang/GCTT, pull requests merged in 2019-09, with the labels that each got.

#1404 【翻译完成】20190108-Avoid package names like base, util, or common
  translated/tech/20190108-Avoid package names like base, util, or common.md
Labels: 校对完成

#1399 【翻译完成】20161218-modern-garbage-collection
  translated/tech/20161218-modern-garbage-collection.md
Labels: 校对中

#1419 【翻译完成】20190829-a-look-at-go-1-13-errors
  translated/tech/20190829-a-look-at-go-1-13-errors.md
Labels: 校对完成

#1408 【翻译完成】20181230-building-immutable-data-structures-in-go
  translated/tech/20181230-building-immutable-data-structures-in-go.md
Labels: request changes, 校对完成

#1432 【完成翻译】20190807-go-thoughts-about-cobra
  translated/tech/20190807-go-thoughts-about-cobra.md
Labels: request changes, 校对完成

#1389 【翻译完成】20190724-Vuejs-Golang-A-Rare-Combination
  translated/tech/20190724-vuejs-golang-a-rare-combination.md
Labels: 校对完成

#1413 【翻译完成】20190810 Go: Monitor pattern
  translated/tech/20190810-go-monitor-pattern.md
Labels: request changes, 校对完成

#1435 【翻译完成】20190802-go-vet-command-is-more-powerful-than-you-think
  translated/tech/20171117-Golang-tutorial-series/20190802-go-vet-command-is-more-powerful-than-you-think.md
Labels: request changes, 校对完成

#1433 【完成翻译】20180717-buffered-and-unbuffered-channels
  translated/tech/20171117-Golang-tutorial-series/20180717-buffered-and-unbuffered-channels.md
Labels: request changes, 校对完成

#1412 【翻译完成】20181204_Find_DNS_records_programmatically
  translated/tech/20181204_Find_DNS_records_programmatically.md
Labels: 校对中

#1395 【完成翻译】20190802-why-you-should-use-a-go-module-proxy
  translated/tech/20190802-why-you-should-use-a-go-module-proxy.md
Labels: 校对完成

#1454 【翻译完成】20190920-A-mini-guide-Build-a-REST-API-as-a-Go-microservice-together-with-MySQL
  translated/tech/20190920-A-mini-guide-Build-a-REST-API-as-a-Go-microservice-together-with-MySQL.md
Labels: request changes, 校对完成

#1456 【翻译完成】20190920-GoLang - Initial Experience #1450
  translated/tech/20190920-GoLang-Initial-Experience.md
Labels: request changes, 校对完成
