Repository studygolang/GCTT, pull requests merged in 2019-12, with the labels that each got.

#1488 翻译完成: 20191107-go-modules-v2-and-beyond.md
  translated/tech/20191107-go-modules-v2-and-beyond.md
Labels: 校对中

#1505 【翻译完成】20190717-The-cost-of-syntactic-sugar-in-Go
  translated/tech/20190717-The-cost-of-syntactic-sugar-in-Go.md
Labels: 校对完成

#1497 翻译完成 20190222-Decoding-Why-GoLang-Stands-Apart-from-the-Other-Languages
  translated/tech/20190222-Decoding-Why-GoLang-Stands-Apart-from-the-Other-Languages.md
Labels: 校对完成

#1517 【翻译完成】20190922-building-a-fast-modern-web-crawler
  translated/tech/20190922-building-a-fast-modern-web-crawler.md
Labels: 校对完成

#1462 【翻译完成】20190920 Create-your-developer-portfolio-using-Hugo-and-Github-Pages
  translated/tech/20190920-Create-your-developer-portfolio-using-Hugo-and-Github-Pages.md
Labels: 校对完成

#1499 Translate 20191125-Go-Goroutine-OS-Thread-and-CPU-Management.
  translated/tech/20191125-Go-Goroutine-OS-Thread-and-CPU-Management.md
Labels: 校对完成

#1500 【翻译完成】20191120-Beating-C-with-70-Lines-of-Go.md
  translated/tech/20191120-Beating-C-with-70-Lines-of-Go.md
Labels: 校对完成

#1510 【翻译完成】 20191127-Circuit-Breaker-and-Retry
  translated/tech/20191127-Circuit-Breaker-and-Retry.md
Labels: 校对完成

#1460 【翻译完成】 20160828-how-to-call-privite-functions-in-go.md
  translated/tech/20160828-how-to-call-privite-functions-in-go.md
Labels: 校对完成

#1489 【翻译完成】20191105-I-wrote-Gocache-a-complete-and-extensible-Go-cache-library
  translated/tech/20191105-I-wrote-Gocache-a-complete-and-extensible-Go-cache-library.md
Labels: 校对完成

#1504 【翻译完成】20190920-Migrating-From-Travis-To-Github-Actions.md translated
  translated/tech/20191107-Migrating-From-Travis-To-Github-Actions.md
Labels: 校对中

#1528 【翻译完成】20191201-Introduction-to-Protobuf-Messages
  translated/tech/20191201-Introduction-to-Protobuf-Messages.md
Labels: 校对完成

#1373 【翻译完成】20190227-Step-driven-evaluation
  translated/tech/20190227-Step-driven-evaluation.md
Labels: request changes, 校对完成

#1396 【翻译完成】 20190725 Deploy a Golang App in 5 Minutes
  translated/tech/20190725-Deploy-a-Golang-App-in-5-Minutes.md
Labels: 校对完成

#1407 [完成翻译] 20190826 How I organize packages in Go
  translated/tech/2019-08-26-how-i-organize-packages-in-go.md
Labels: 校对完成

#1572 【翻译完成】20191211 the potential issue with go s strings
  translated/tech/20191211-The-potential-issue-with-Go-s-strings.md
Labels: request changes

#1529 【翻译完成】 20190829-Using-w-and-s-Flags-in-Golang
  translated/tech/20190829-Using-w-and-s-Flags-in-Golang.md
Labels: 校对完成

#1470 翻译完成 20190725-GopherCon-2019-Go-Module-Proxy-Life-of-a-query
  translated/tech/20190725-GopherCon-2019-Go-Module-Proxy-Life-of-a-query.md
Labels: 校对完成

#1506 【翻译完成】20191003-Integeration-testing-in-go-part-2.md
  translated/tech/20191003-Integeration-testing-in-go-part-2.md
Labels: 校对完成

#1519 【翻译完成】20190725 Writing delightful HTTP middleware in Go
  translated/tech/20190725-Writing-delightful-HTTP-middleware-in-Go.md
Labels: request changes, 校对完成

#1571 【翻译完成】20191103 go how does the garbage collector mark the memory
  translated/tech/20191103-Go-How-Does-the-Garbage-Collector-Mark-the-Memory.md
Labels: 校对完成

#1587 【翻译完成】20191211 Learning about Go's unaddressable values and slicing
  translated/tech/Learning about Go's unaddressable values and slicing.md
Labels: 校对完成

#1577 【完成翻译】-20191202-Go-How-Are-Random-Numbers-Generated
  translated/tech/20191202-Go-How-Are-Random-Numbers-Generated.md
Labels: 校对完成
