Repository studygolang/GCTT, pull requests merged in 2019-10, with the labels that each got.

#1294 【翻译完成】20190415 Advanced testing patterns in Go
  translated/tech/20190415 Advanced testing patterns in Go.md
Labels: request changes, 校对完成

#1313 【完成翻译】20190225-Design-of-a-Modern-Cache-Part-Deux
  translated/tech/20190225-Design-of-a-Modern-Cache-Pare-Deux.md
Labels: 校对完成

#1443 【翻译完成】20190814-go-understand-the-empty-interface
  translated/tech/20171117-Golang-tutorial-series/20190814-go-understand-the-empty-interface.md
Labels: 校对中

#1329 【翻译完成】20190530-Benefits-of-Using-Microservice-Architecture-in-Go
  translated/tech/20190530-Benefits-of-Using-Microservice-Architecture-in-Go.md
Labels: request changes, 校对完成

#1453 【翻译完成】20190906-Go-Concurrency-Bugs-in-Go.md Closes #1427
  translated/tech/20190906-Go-Concurrency-Bugs-in-Go.md
Labels: request changes, 校对完成

#1414 【翻译完成】20180330-Go-On-Very-Small-Hardware-Part3
  translated/tech/20180330-Go-On-Very-Small-Hardware-Part3.md
Labels: 校对中
