Repository studygolang/GCTT, pull requests merged in 2020-10, with the labels that each got.

#1815 【翻译完成】20200422 Why Golang? Settling the Debate Once and For All
  translated/tech/20200422-Why-Golang-Settling-the-Debate-Once-and-For-All.md
Labels: 校对完成

#1822 【翻译完成】20200813 Go: Built-in Functions Optimizations
  translated/tech/20200813-Go-Built-in-Functions-Optimizations.md
Labels: 校对完成

#1825 【翻译完成】20200610 Go: String & Conversion Optimization
  translated/tech/20200610-Go-String-and-Conversion-Optimization.md
Labels: request changes, 校对完成

#1830 【翻译完成】20201002 Go: How Does a Program Recover?
  translated/tech/20201002-Go-How-Does-a-Program-Recover.md
Labels: request changes
