Repository studygolang/GCTT, pull requests merged in 2020-05, with the labels that each got.

#1669 【翻译完成】20200413 go aliases simple and efficient
  translated/tech/20200413-Go-Aliases-Simple-and-Efficient.md
Labels: 校对完成

#1661 【翻译完成】20190615 Go: How Does defer Statement Work?
  translated/tech/20190615-Go-How-Does-defer-Statement-Work.md
Labels: 校对完成

#1673 【翻译完成】20190622 Go: Shared Objects for Cross Team Collaboration
  translated/tech/20190622-Go-Shared-Objects-for-Cross-Team-Collaboration.md
Labels: 校对中

#1671 【翻译完成】20200401 go how does a goroutine start and exit
  translated/tech/20200401-Go-How-Does-a-Goroutine-Start-and-Exit.md
Labels: 校对完成

#1676 【翻译完成】20200201 Go: How Are Loops Translated to Assembly?
  translated/tech/20200201-Go How-Are-Loops-Translated-to-Assembly.md
Labels: 校对中

#1677 【翻译完成】20200408 Implementing RSA Encryption and Signing in Golang
  translated/tech/20200408-Implementing-RSA-Encryption-and-Signing-in-Golang.md
Labels: 校对完成

#1684 【翻译完成】20191211 CGo's Go string functions explained
  translated/tech/20191211-CGos-Go-string-functions-explained.md
Labels: 校对完成

#1693 【翻译完成】20200501-Go-Asynchronous-Preemption
  translated/tech/20200501-Go-Asynchronous-Preemption.md
Labels: 校对完成

#1678 【翻译完成】20190111 Go advanced benchmarking
  translated/tech/20190111-Go-advanced-benchmarking.md
Labels: 校对完成

#1683 [翻译完成]20200418 Naming Conventions in Go: Short but Descriptive #1682
  translated/tech/20200418 Naming Conventions in Go: Short but Descriptive.md
Labels: 校对完成

#1679 [翻译完成] 20191213 Go: Goroutine and Preemption
  translated/tech/20191213-Go-Goroutine-and-Preemption.md
Labels: 校对完成

#1716 【翻译完成】20200309-Go-gsignal-Master-of-Signals
  translated/tech/20200309-Go-gsignal-Master-of-Signals.md
Labels: 校对完成

#1718 【翻译完成】20200505 go samples collection with pprof
  translated/tech/20200505-Go-Samples-Collection-with-pprof.md
Labels: 校对完成

#1721 【翻译完成】20200503-slices-from-the-ground-up.md
  translated/tech/20200503-slices-from-the-ground-up.md
Labels: 校对完成

#1720 【翻译完成】20190602 Go: How Does the Goroutine Stack Size Evolve?
  translated/tech/20190602-Go-How-Does-the-Goroutine-Stack-Size-Evolve.md
Labels: 校对完成

#1722 【翻译完成】20200503-there-is-no-pass-by-reference-in-go
  translated/tech/20200503-there-is-no-pass-by-reference-in-go.md
Labels: 校对完成

#1725 【翻译完成】20200102 Go: Concurrency & Scheduler Affinity
  translated/tech/20200102-Go-Concurrency-And-Scheduler-Affinity.md
Labels: 校对完成

#1730 【翻译完成】20200516 Writing Great Go Code
  translated/tech/20200516-Writing-Great-Go-Code.md
Labels: 校对完成

#1724 【翻译完成】20191109-Lets-Create-a-Simple-Load-Balancer-With-Go
  translated/tech/20191109-Lets-Create-a-Simple-Load-Balancer-With-Go.md
Labels: 校对完成

#1737 【翻译完成】20191025 Go: Fuzz Testing in Go
  translated/tech/20191025-Go-Fuzz-Testing-in-Go.md
Labels: 校对完成

#1739 【翻译完成】20200524-Diamond-interface-composition-in-Go-114
  translated/tech/20200524-Diamond-interface-composition-in-Go-114.md
Labels: 校对完成

#1745 【翻译完成】20191210 Go: GOMAXPROCS & Live Updates
  translated/tech/20191210-Go-GOMAXPROCS-Live-Updates.md
Labels: 校对完成

#1689 【翻译完成】Go: Ordering in Select Statements
  translated/tech/20200429-Go Ordering in Select Statements.md
Labels: 校对完成

#1674 完成翻译:20181113 Building an API with GraphQL and Go
  translated/tech/[20181113]-Building-an-API-with-GraphQL-and-Go.md
Labels: request changes

#1732 【翻译完成】20200510-Go-How-to-Take-Advantage-of-the-Symbols-Table
  translated/tech/20200510-Go-How-to-Take-Advantage-of-the-Symbols-Table.md
Labels: 校对完成
